# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=250, verbose_name='numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='', max_length=250, verbose_name='poste occupé'),
        ),
    ]
