# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lost_password_token',
            field=models.CharField(blank=True, max_length=36, verbose_name='jeton mot de passe perdu'),
        ),
    ]
