# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_lost_password_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_email_token',
            field=models.CharField(blank=True, max_length=36, verbose_name='jeton email'),
        ),
        migrations.AddField(
            model_name='user',
            name='confirm_phone_token',
            field=models.CharField(blank=True, max_length=6, verbose_name='jeton téléphone'),
        ),
    ]
