# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 12:40
from __future__ import unicode_literals

import apps.core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='adresse')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='longitude')),
                ('street_number', models.CharField(blank=True, max_length=250, verbose_name='numéro de rue')),
                ('route', models.CharField(blank=True, max_length=250, verbose_name='nom de rue')),
                ('cp', models.CharField(blank=True, max_length=250, verbose_name='code postal')),
                ('locality', models.CharField(blank=True, max_length=250, verbose_name='ville')),
                ('administrative_area_level_1', models.CharField(blank=True, max_length=250, verbose_name='région')),
                ('administrative_area_level_2', models.CharField(blank=True, max_length=250, verbose_name='département')),
                ('country', models.CharField(blank=True, max_length=250, verbose_name='pays')),
                ('company', models.CharField(max_length=250, verbose_name='raison sociale')),
                ('website', models.CharField(blank=True, max_length=250, verbose_name='site web')),
                ('description', models.TextField(blank=True, max_length=250, verbose_name='description')),
                ('phone', models.CharField(blank=True, max_length=250, verbose_name='phone')),
                ('ca', models.CharField(blank=True, max_length=250, verbose_name="chiffre d'affaire")),
                ('logo', apps.core.fields.ImageField(blank=True, default='pro/logo/default.jpg', upload_to='', verbose_name='logo')),
                ('employes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.Employee', verbose_name="nombre d'employés")),
                ('industry', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='data.Industry', verbose_name="secteur d'activité")),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
