# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='est actif'),
        ),
    ]
