# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0002_pro_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pro',
            options={'verbose_name': 'pro', 'verbose_name_plural': 'pros'},
        ),
    ]
