# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro', '0003_auto_20170127_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pro',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
    ]
