# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20170118_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobquestion',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='job.Job', verbose_name='offre'),
        ),
        migrations.AlterField(
            model_name='jobquestion',
            name='question',
            field=models.CharField(max_length=250, verbose_name='question'),
        ),
    ]
