# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_job_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='starting_date',
            field=models.CharField(max_length=250, verbose_name='disponibilite'),
        ),
    ]
