# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

APPLICANT_JOB_NEW_MATCHING = 'APPLICANT_JOB_NEW_MATCHING'
APPLICANT_CANDIDACY_REQUESTED = 'APPLICANT_CANDIDACY_REQUESTED'
APPLICANT_CANDIDACY_APPROVED = 'APPLICANT_CANDIDACY_APPROVED'
APPLICANT_CANDIDACY_DISAPPROVED = 'APPLICANT_CANDIDACY_DISAPPROVED'
PRO_JOB_ADDED = 'PRO_JOB_ADDED'
PRO_JOB_UPDATED = 'PRO_JOB_UPDATED'
PRO_JOB_PUBLISHED = 'PRO_JOB_PUBLISHED'
PRO_JOB_DELETED = 'PRO_JOB_DELETED'
PRO_JOB_LIKED = 'PRO_JOB_LIKED'
PRO_JOB_NEW_CANDIDACY = 'PRO_JOB_NEW_CANDIDACY'
PRO_COLLABORATOR_ADDED = 'PRO_COLLABORATOR_ADDED'
PRO_COLLABORATOR_DELETED = 'PRO_COLLABORATOR_DELETED'
PRO_CANDIDACY_NEW_COMMENT = 'PRO_CANDIDACY_NEW_COMMENT'
NEW_MESSAGE = 'NEW_MESSAGE'
