# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 15:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_request_credits'),
        ('applicant', '0004_auto_20170124_1003'),
        ('candidacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidacy',
            unique_together=set([('job', 'applicant')]),
        ),
    ]
