# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0002_auto_20170126_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidacy',
            name='matching_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='score matching'),
        ),
    ]
