# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 09:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidacy', '0002_auto_20170126_1507'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidacyMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='message')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidacy.Candidacy', verbose_name='candidature')),
                ('emmiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='émmeteur')),
            ],
        ),
        migrations.CreateModel(
            name='CandidacyMessageRead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='est lu')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='date de dernière lecture')),
                ('candidacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidacy.Candidacy', verbose_name='candidature')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
        ),
    ]
