# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidacy', '0002_auto_20170126_1507'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidacymessage',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='candidacymessageread',
            options={'verbose_name': 'message lu', 'verbose_name_plural': 'messages lu'},
        ),
        migrations.AlterUniqueTogether(
            name='candidacymessageread',
            unique_together=set([('candidacy', 'user')]),
        ),
    ]
