# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20170208_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidacymessageread',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de dernière lecture'),
        ),
    ]
