# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-20 11:10
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_auto_20170120_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='wanted_jobs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, verbose_name='job'), blank=True, null=True, size=None, verbose_name='postes recherchés'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='wanted_skills',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250, verbose_name='skill'), blank=True, null=True, size=None, verbose_name='compétences recherchées'),
        ),
    ]
