# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_auto_20170120_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Formation',
            new_name='ApplicantEducation',
        ),
        migrations.RenameModel(
            old_name='Experience',
            new_name='ApplicantExperience',
        ),
        migrations.RenameModel(
            old_name='Interest',
            new_name='ApplicantInterest',
        ),
        migrations.RenameModel(
            old_name='Language',
            new_name='ApplicantLanguage',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='ApplicantSkill',
        ),
    ]
