# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_auto_20170124_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicanteducation',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='applicant.Applicant', verbose_name='postulant'),
        ),
        migrations.AlterField(
            model_name='applicantexperience',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='applicant.Applicant', verbose_name='postulant'),
        ),
        migrations.AlterField(
            model_name='applicantinterest',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='applicant.Applicant', verbose_name='postulant'),
        ),
        migrations.AlterField(
            model_name='applicantlanguage',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='applicant.Applicant', verbose_name='postulant'),
        ),
        migrations.AlterField(
            model_name='applicantskill',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='applicant.Applicant', verbose_name='postulant'),
        ),
    ]
